<?php

declare(strict_types=1);

namespace App\Mcp\Tools\Concerns;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Illuminate\JsonSchema\Types\Type;
use Laravel\Mcp\Response;
use Laravel\Mcp\ResponseFactory;

trait GeneratesEventImageResponse
{
    /**
     * @return array<string, Type>
     */
    protected function eventImageInputSchema(JsonSchema $schema): array
    {
        return [
            'event_key' => $schema->string()
                ->required()
                ->min(1)
                ->description('Event UUID or slug/route key. Example: tadabbur-isu-semasa-ummah-qdkhqqn.'),
            'creative_direction' => $schema->string()
                ->nullable()
                ->description('Optional additional design direction from the user, such as mood, color preference, typography style, or what to emphasize.'),
            'include_existing_media' => $schema->boolean()
                ->nullable()
                ->default(true)
                ->description('Whether to include existing event media from the target collection as reference media when available.'),
            'max_reference_media' => $schema->integer()
                ->nullable()
                ->min(0)
                ->max(8)
                ->default(6)
                ->description('Maximum number of selected reference images to attach to the image-generation request.'),
        ];
    }

    /**
     * @return array<string, Type>
     */
    protected function eventImageOutputSchema(JsonSchema $schema): array
    {
        return [
            'event' => $schema->object([
                'id' => $schema->string()->required(),
                'route_key' => $schema->string()->required(),
                'slug' => $schema->string()->required(),
                'title' => $schema->string()->required(),
                'public_url' => $schema->string()->required(),
            ])->required(),
            'target' => $schema->object([
                'collection' => $schema->string()->required(),
                'label' => $schema->string()->required(),
                'aspect_ratio' => $schema->string()->required(),
                'output_width' => $schema->integer()->required(),
                'output_height' => $schema->integer()->required(),
            ])->required(),
            'prompt' => $schema->string()
                ->required()
                ->description('Prompt used for the image-generation request.'),
            'upload_spec' => $schema->object()->required(),
            'reference_media' => $schema->array()
                ->required()
                ->items($schema->object())
                ->description('Selected event and relation media considered for the generation request.'),
            'source_data' => $schema->object()
                ->required()
                ->description('Direct event attributes, computed values, relation data, and available media used to construct the prompt.'),
            'generated_media' => $schema->object()
                ->required()
                ->description('The stored Spatie MediaLibrary item generated by this tool.'),
            'generation' => $schema->object()->required(),
            'usage' => $schema->object()->required(),
        ];
    }

    /**
     * @param  array{
     *   payload: array<string, mixed>,
     *   image_contents: string,
     *   image_mime_type: string
     * }  $result
     */
    protected function eventImageResponse(array $result): ResponseFactory
    {
        $payload = $result['payload'];
        $target = is_array($payload['target'] ?? null) ? $payload['target'] : [];
        $event = is_array($payload['event'] ?? null) ? $payload['event'] : [];
        $generatedMedia = is_array($payload['generated_media'] ?? null) ? $payload['generated_media'] : [];
        $collection = (string) ($target['collection'] ?? $generatedMedia['collection'] ?? 'media');
        $title = (string) ($event['title'] ?? 'event');
        $url = (string) ($generatedMedia['url'] ?? '');

        $text = trim("Generated {$collection} image for {$title}.");

        if ($url !== '') {
            $text .= "\nSaved media URL: {$url}";
        }

        return Response::make([
            Response::text($text),
            Response::image($result['image_contents'], $result['image_mime_type'])
                ->withMeta([
                    'collection' => $collection,
                    'event_key' => $event['route_key'] ?? null,
                    'media_id' => $generatedMedia['id'] ?? null,
                    'url' => $url !== '' ? $url : null,
                    'required_aspect_ratio' => $target['aspect_ratio'] ?? null,
                ]),
        ])->withStructuredContent($payload);
    }

    protected function booleanArgument(mixed $value, bool $default): bool
    {
        if ($value === null) {
            return $default;
        }

        if (is_bool($value)) {
            return $value;
        }

        $normalized = filter_var($value, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);

        return is_bool($normalized) ? $normalized : $default;
    }

    protected function integerArgument(mixed $value, int $default, int $min, int $max): int
    {
        if (! is_numeric($value)) {
            return $default;
        }

        return max($min, min($max, (int) $value));
    }
}
